name: Python application

on:
  push:
    branches: 
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Set up Python 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install any dependencies (if you have any)

    - name: Run tests
      run: |
        python -m unittest discover  # Discover and run all tests
